name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check types
        id: types
        run: composer types:check

      - name: Check style
        id: style
        run: composer style:check

      - name: Run tests
        id: tests
        run: composer tests:run:with-coverage -- --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        id: upload-coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
